[package]
name = "achlys-core"
version.workspace = true
edition.workspace = true
authors.workspace = true


[dependencies]
libafl.workspace = true
libafl_bolts.workspace = true
achlys-bridge = { path = "../bridge" }
achlys-protocol = { path = "../protocol" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
